## This configuration was generated by terraform-provider-oci


resource "random_string" "redis_password" {
  length      = 24
  special     = false
  min_lower   = 2
  min_upper   = 2
  min_numeric = 4
}

resource "oci_redis_redis_cluster" "redis" {
  cluster_mode   = "NONSHARDED"
  compartment_id = var.compartment_id
  display_name   = var.display_name
  # freeform_tags = {
  # }
  node_count         = var.node_count
  node_memory_in_gbs = var.node_memory
  nsg_ids = [
  ]
  software_version = "VALKEY_7_2"
  subnet_id        = var.subnet_id
}


# # security list to allow access from any node pool subnet
# resource "oci_core_security_list" "redis_sec_list" {
#   count          = var.use_existing_vcn ? 0 : 1
#   compartment_id = var.vcn_compartment_id
#   display_name   = "Redis"
#   vcn_id         = oci_core_vcn.oke_vcn[0].id
#   defined_tags   = var.vcn_tags

#   dynamic "ingress_security_rules" {
#     iterator = cidr
#     for_each = local.node_pool_subnets_cidrs
#     content {
#       description = "Access to Redis from nodes"
#       protocol    = "6"
#       source      = cidr.value
#       stateless   = false

#       tcp_options {
#         min = 6379
#         max = 6379
#       }
#     }
#   }
# }
