## This configuration was generated by terraform-provider-oci

data "oci_psql_configurations" "configurations" {

  #Optional
  compartment_id = var.cluster_compartment_id
}

resource "random_string" "postgres_password" {
  length      = 20
  special     = true
  min_lower   = 2
  min_upper   = 2
  min_special = 2
  min_numeric = 4
}

# output "psql_config" {
#   value = data.oci_psql_configurations.configurations
# }

resource "oci_psql_db_system" "langfuse_postgres" {
  #apply_config = <<Optional value not found in discovery>>
  compartment_id = var.cluster_compartment_id
  #config_id      = "ocid1.postgresqldefaultconfiguration.oc1.us-chicago-1.amaaaaaayn42exya5plpxgtlvjw76xdsfrac5ea7gunt6so5yfuberneo4cq"
  credentials {
    #Required
    password_details {
      #Required
      password_type = "PLAIN_TEXT"

      #Optional
      password = random_string.postgres_password.result
      # secret_id = oci_vault_secret.test_secret.id
      # secret_version = var.db_system_credentials_password_details_secret_version
    }
    username = "langfuse"
  }
  db_version = "16"
  #description = <<Optional value not found in discovery>>
  display_name = "langfuse"
  freeform_tags = {
  }
  instance_count              = "1"
  instance_memory_size_in_gbs = "64"
  instance_ocpu_count         = "2"
  #instances_details = <<Optional value not found in discovery>>
  management_policy {
    backup_policy {
      backup_start = "00:00"
      #days_of_the_month = <<Optional value not found in discovery>>
      #days_of_the_week = <<Optional value not found in discovery>>
      kind           = "DAILY"
      retention_days = "30"
    }
    maintenance_window_start = "MON 16:30"
  }
  network_details {
    is_reader_endpoint_enabled = "false"
    nsg_ids = [
    ]
    #primary_db_endpoint_private_ip = "10.0.22.48"
    subnet_id = var.use_existing_vcn ? local.node_pools[0]["subnet"] : oci_core_subnet.oke_nodepool_subnet[0].id
  }
  #patch_operations = <<Optional value not found in discovery>>
  shape = "PostgreSQL.VM.Standard.E6.Flex"
  source {
    #backup_id = <<Optional value not found in discovery>>
    #is_having_restore_config_overrides = <<Optional value not found in discovery>>
    source_type = "NONE"
  }
  storage_details {
    #availability_domain = <<Optional value not found in discovery>>
    iops                  = "75000"
    is_regionally_durable = "true"
    system_type           = "OCI_OPTIMIZED_STORAGE"
  }
  system_type = "OCI_OPTIMIZED_STORAGE"
}


data "oci_psql_db_system_connection_detail" "psql_connection_detail" {
  db_system_id = oci_psql_db_system.langfuse_postgres.id
}

locals {
  psql_cert     = data.oci_psql_db_system_connection_detail.psql_connection_detail.ca_certificate
  psql_endpoint = data.oci_psql_db_system_connection_detail.psql_connection_detail.primary_db_endpoint
}



# # security list to allow access from any node pool subnet
# resource "oci_core_security_list" "psql_sec_list" {
#   count          = var.use_existing_vcn ? 0 : 1
#   compartment_id = var.vcn_compartment_id
#   display_name   = "Postgres"
#   vcn_id         = oci_core_vcn.oke_vcn[0].id
#   defined_tags   = var.vcn_tags

#   dynamic "ingress_security_rules" {
#     iterator = cidr
#     for_each = local.node_pool_subnets_cidrs
#     content {
#       description = "Access to Postgres from nodes"
#       protocol    = "6"
#       source      = cidr.value
#       stateless   = false

#       tcp_options {
#         min = 5432
#         max = 5432
#       }
#     }
#   }
# }
