## This configuration was generated by terraform-provider-oci

resource "oci_redis_redis_cluster" "redis" {
  cluster_mode   = "NONSHARDED"
  compartment_id = var.cluster_compartment_id
  display_name   = "LangFuse"
  freeform_tags = {
  }
  node_count         = "1"
  node_memory_in_gbs = "16"
  nsg_ids = [
  ]
  #shard_count = <<Optional value not found in discovery>>
  software_version = "VALKEY_7_2"
  subnet_id        = var.use_existing_vcn ? local.node_pools[0]["subnet"] : oci_core_subnet.oke_nodepool_subnet[0].id
}


# # security list to allow access from any node pool subnet
# resource "oci_core_security_list" "redis_sec_list" {
#   count          = var.use_existing_vcn ? 0 : 1
#   compartment_id = var.vcn_compartment_id
#   display_name   = "Redis"
#   vcn_id         = oci_core_vcn.oke_vcn[0].id
#   defined_tags   = var.vcn_tags

#   dynamic "ingress_security_rules" {
#     iterator = cidr
#     for_each = local.node_pool_subnets_cidrs
#     content {
#       description = "Access to Redis from nodes"
#       protocol    = "6"
#       source      = cidr.value
#       stateless   = false

#       tcp_options {
#         min = 6379
#         max = 6379
#       }
#     }
#   }
# }
