region                 = "us-chicago-1"
tenancy_ocid           = "ocid1.tenancy.oc1..aaaa"
vcn_compartment_id     = "ocid1.compartment.oc1..aaaa"
cluster_compartment_id = "ocid1.compartment.oc1..aaaa"
use_existing_vcn       = true
vcn_id                 = "ocid1.vcn.oc1..aaaa"
# Explicitly empty to override any terraform.tfvars values and trigger validation failures
kubernetes_endpoint_subnet         = null
public_lb_subnet                   = null
np1_subnet                         = null
node_pool_count                    = 1
create_bastion                     = false
langfuse_s3_access_key             = "fake-access"
langfuse_s3_secret_key             = "fake-secret"
ssh_public_key                     = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdummykey"
devops_compartment_id              = "ocid1.compartment.oc1..aaaa"
kubernetes_version                 = "v1.34.2"
secrets_store_vault_compartment_id = "ocid1.compartment.oc1..aaaa"
secrets_store_vault_id             = "ocid1.vault.oc1..aaaa"
secrets_store_key_id               = "ocid1.key.oc1..aaaa"
