## Copyright © 2022-2026, Oracle and/or its affiliates.
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: letsencrypt-staging
spec:
  acme:
    # profile, shortlived to be able to provision IP certs
    profile: shortlived
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef: 
      name: letsencrypt-issuer-staging-account-key
    solvers: 
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: langfuse-gateway
            namespace: langfuse
            sectionName: http
            kind: Gateway
          labels:
            acme.cert-manager.io/http01-solver: "true"
          serviceType: ClusterIP
          # podTemplate:
          #   metadata:
          #     annotations:
          #       oci-native-ingress.oraclecloud.com/http-listener-port: "80"
          #       oci-native-ingress.oraclecloud.com/https-listener-port: "443"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: letsencrypt-prod
spec:
  acme:
    # profile, shortlived to be able to provision IP certs
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef: 
      name: letsencrypt-issuer-prod-account-key
    solvers: 
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: langfuse-gateway
            namespace: langfuse
            sectionName: http
            kind: Gateway
          labels:
            acme.cert-manager.io/http01-solver: "true"
          serviceType: ClusterIP
          # podTemplate:
          #   metadata:
          #     annotations:
          #       oci-native-ingress.oraclecloud.com/http-listener-port: "80"
          #       oci-native-ingress.oraclecloud.com/https-listener-port: "443"
