apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: langfuse-from-vault
  namespace: langfuse
spec:
  provider: oci
  parameters:
    secrets: |
      # langfuse password hashing
      - name: LANGFUSE_ENCRYPTION_KEY
        stage: CURRENT
        fileName: encryption-key
      - name: LANGFUSE_SALT
        stage: CURRENT
        fileName: salt
      - name: LANGFUSE_NEXTAUTH_SECRET
        stage: CURRENT
        fileName: nextauth-secret
      - name: LANGFUSE_CLICKHOUSE_PASSWORD
        stage: CURRENT
        fileName: clickhouse-password
      - name: LANGFUSE_REDIS_PASSWORD
        stage: CURRENT
        fileName: redis-password

      # langfuse IDCS secrets
      - name: LANGFUSE_CLIENT_ID
        stage: CURRENT
        fileName: client-id
      - name: LANGFUSE_CLIENT_SECRET
        stage: CURRENT
        fileName: client-secret
      - name: LANGFUSE_ISSUER
        stage: CURRENT
        fileName: issuer

      # Langfuse Object Storage access keys
      - name: LANGFUSE_S3_ACCESS_KEY
        stage: CURRENT
        fileName: s3-access-key
      - name: LANGFUSE_S3_SECRET_KEY
        stage: CURRENT
        fileName: s3-secret-key

      # langfuse Postgres cert (mount-only)
      - name: CaCertificate-langfuse.pub
        stage: CURRENT
        fileName: CaCertificate-langfuse.pub

      # langfuse postgres password and connection string
      - name: LANGFUSE_POSTGRES_PASSWORD
        stage: CURRENT
        fileName: postgres-password
      - name: LANGFUSE_DATABASE_URL
        stage: CURRENT
        fileName: database-url
    authType: workload
    vaultId: ${SECRET_STORE_VAULT_ID}

  # SecretObject defines the desired state of synced K8s secret objects
  secretObjects:
    - secretName: langfuse-from-vault
      type: Opaque
      data:
        - key: encryption-key
          objectName: encryption-key
        - key: salt
          objectName: salt
        - key: nextauth-secret
          objectName: nextauth-secret
        - key: clickhouse-password
          objectName: clickhouse-password
        - key: redis-password
          objectName: redis-password

    - secretName: langfuse-idcs-from-vault
      type: Opaque
      data:
        - key: client-id
          objectName: client-id
        - key: client-secret
          objectName: client-secret
        - key: issuer
          objectName: issuer

    - secretName: langfuse-s3-from-vault
      type: Opaque
      data:
        - key: s3-access-key
          objectName: s3-access-key
        - key: s3-secret-key
          objectName: s3-secret-key

    - secretName: langfuse-postgres-from-vault
      type: Opaque
      data:
        - key: postgres-password
          objectName: postgres-password
        - key: database-url
          objectName: database-url

